### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by DawnSaju** [NETtoSan/Makex-sources#12]
Hello NETtoSan, 

My name's Dawn Saju and I'm currently competing in the Makex competition. I'm having a bit of trouble with the components since the documentation provided is a bit lacking, and I noticed that the NovaPi Python uploading application only shows CyberPi to connect. Do you think you could lend a hand? Thanks a bunch! 😊

**Comment by NETtoSan** [comment]
The Makeblock's Python application only supports CyberPi, if I remember correctly. if you want to code Novapi in python you would have to switch to Python in Makeblock's block editing mode 

The Novapi's documentation is also lagging because from what I have heard. it's a competition-focused programming board. So there aren't many source codes and documentation available. The only thing I've done is convert each Novapi's function into Python code.

Also, I'm not an employee xD. I'm just a contestant in um... 2022 MakeX international competition.

**Comment by DawnSaju** [comment]
Could you explain how to switch from block to Python? I tried Python code editor but as you said it only shows CyberPi.

Thank you so much for your immense support!

**Comment by NETtoSan** [comment]
Use this tab right from mblock
![image](https://user-images.githubusercontent.com/62388769/233135376-c4c1fb62-70df-4be9-93a8-00cf6abf6637.png)

Instead of going through Python Editor
![image](https://user-images.githubusercontent.com/62388769/233135700-2246dab8-0ed9-453e-8d60-992ed3195da0.png)

However. it's very basic and it does not provide that much functionality.

**Comment by DawnSaju** [comment]
Thanks a lot, One last question is there any python program that I can test to ensure the board is working fine like any outputs in the command line or something like that.

**Comment by NETtoSan** [comment]
I haven't tried to make it output into a command line. However, I test things out by pairing it with **Dual RGB sensor** and using its RGB light as an indicator. For a numeric output from sensors. I've used the LED matrix
![image](https://user-images.githubusercontent.com/62388769/233138299-219dea72-178c-4784-b441-250ac7f7a8ed.png)
 

For example
: If an IR sensor sees things less than 20cm. Change it to red. Otherwise, change it to whatever color


This is the only we've tested things out throughout the competition. Due to little time and lack of parts, hope this helps!

**Comment by DawnSaju** [comment]
Awesome, I really appreciate your immense support.

**Comment by NETtoSan** [comment]
Good luck with the competition! By the way, is this MakeX Challenge? or something else

**Comment by DawnSaju** [comment]
Yes it is MakeX Challenge, this is my first time dealing with these type of resources so bare with my silly questions.

**Comment by NETtoSan** [comment]
Ooh! Wish you the best of luck!

**Comment by NETtoSan** [comment]
oops wrong button xD

**Comment by DawnSaju** [comment]
If I have any more doubts, is it fine if I contact you?

**Comment by NETtoSan** [comment]
Sure thing!
If you want my discord. It's Niuki#0001
